'use strict';
// Nur Vorschlagsdaten. Die gemeinsamen Messfragen sind keine zweite App-Rechenquelle.
window.BESONDERHEITEN_ERWEITERUNG = [
  {
    id:'rueckeroberung', bereich:'rekorde', art:'mark', kategorie:'Bestmarken', titel:'Die Rückeroberung', status:'Abgeschlossener Verlauf',
    frage:'Die größte persönliche Elo-Talfahrt, aus der jemand innerhalb derselben Saison wieder zum vorherigen Höchststand zurückkehrt.',
    wert:'80 Elo zurückgeholt', person:'100 → 20 → 100 · Beispiel', grafik:'erweiterung', bild:{typ:'weg',werte:[100,70,20,55,100],einheit:'Elo'},
    basis:'30 Partien, geschlossene Rückkehr', achse:'Saisonhoch → Tief → Rückkehr',
    abgrenzung:'Gipfel misst die absolute Höhe, großer Sprung den Tagesgewinn. Hier zählt ein abgeschlossener Weg aus einer Talfahrt.',
    mind:'30 Laufbahnpartien und eine tatsächlich geschlossene Talfahrt. Keine Mindesttiefe: auch zwei Elo können eine Bestmarke sein. Nur kanonische Vor-/Nach-Match-Elo, keine zweite Rechnung.',
    rechnung:'Innerhalb jeder Saison das laufende persönliche Elo-Hoch führen. Der erste niedrigere Stand eröffnet eine Talfahrt mit diesem festen Anker. Tiefsten folgenden Stand merken; erstes Wiedererreichen oder Übersteigen des Ankers schließt. Wert = Anker minus Tief. Danach beginnt die nächste mögliche Talfahrt. Saisonreset verwirft offene Fälle und zählt nie als Verlust oder Rückkehr.',
    gegenbeispiel:'100→20→100 ergibt 80. 500→490→510 ergibt nur zehn, obwohl die absolute Elo viel höher liegt. Ein offenes 100→20 ist noch keine Rückeroberung.',
    risiko:'Saisonstart ist der offizielle Startstand, kein erfundener Karrierehöchststand. Nach einem Sprung über den Anker aktualisiert dessen tatsächlicher Nach-Match-Stand das neue Hoch. Der Beleg nennt Peak, Tief und schließendes Match. Keine Tiefe über mehrere offene Episoden addieren.',
    story:'Martin kehrt zu seinem Saisonhoch zurück. Zwischen 100 und 20 Elo lag eine Talfahrt von 80 – jetzt ist der alte Stand wieder erreicht.',
    beleg:'Erfundener kanonischer Beispielverlauf, keine aus der Liga ausgelesene Elo. Kategorien und Regel sind Vorschläge.'
  },
  {
    id:'serienstopp', bereich:'rekorde', art:'mark', kategorie:'Bestmarken', titel:'Der Serienstopp', status:'Ein besonderer Gegnerlauf',
    frage:'Die längste persönliche Siegesserie eines Gegners, die durch den eigenen Sieg tatsächlich beendet wurde.',
    wert:'13 Siege gestoppt', person:'Johannes, Leon & Martin · Testbasis', grafik:'erweiterung', bild:{typ:'bahn',felder:[['S'],['S'],['S'],['…'],['13 × S'],['Stopp','ende']]},
    basis:'30 Partien, belegte Gegner-Serie', achse:'Serienstand vor dem Match',
    abgrenzung:'Laufstopper und Serienbrecher messen eine Erfolgsquote bei Seriengegnern. Hier ist die größte einzelne gestoppte Serie entscheidend.',
    mind:'30 Laufbahnpartien und ein tatsächlicher Sieg gegen einen Gegner mit einer laufenden persönlichen Siegesserie. Bereits eine Einerserie zählt; kein Dreier- oder Zehner-Mindestwert.',
    rechnung:'Für beide Gegner ihre persönlichen Serien unmittelbar vor diesem Match aus dem globalen Verlauf lesen. Erst nach dieser Aufnahme alle vier Serien fortschreiben. Bei eigenem Sieg den größeren beendeten Einzelwert belegen, nicht beide addieren. Tages- und Monatsgrenzen beenden persönliche Serien nicht.',
    gegenbeispiel:'Ein einziger Sieg gegen eine 13er-Serie kann vor zehn gewonnenen Partien gegen Dreierserien stehen. Es geht nicht um die meisten Siege gegen gute Gegner.',
    risiko:'Persönliche Serie, nicht die Siegesserie eines Duos. Serien aus Spielen ohne den späteren Stopper müssen mitgezählt werden. Die beiden Gewinner dürfen denselben tatsächlichen Stopp teilen. Bei gleichem Wert bleiben alle Halter.',
    story:'Johannes beendet Martins 13er-Serie. So lang war auch der Lauf, den Leon und Martin zuvor gegen Julian stoppten.',
    beleg:'466 Fixture-Partien, kein Live-Stand: Johannes bei m0408 gegen Martin; Leon und Martin bei m0095 gegen Julian. Alle drei halten 13. Die Bahn ist eine Illustration.'
  },
  {
    id:'amplitude', bereich:'rekorde', art:'fuegung', kategorie:'Fügungen', titel:'Die Amplitude', status:'Ein ganzer Tagesweg',
    frage:'Die größte Elo-Spannweite eines eigenen Spieltags – auch wenn am Ende fast wieder derselbe Stand herauskommt.',
    wert:'90 Elo Spannweite', person:'Tagesgewinn nur +10 · Beispiel', grafik:'erweiterung', bild:{typ:'weg',werte:[100,130,40,75,110],einheit:'Elo'},
    basis:'30 Partien, 4 an diesem Tag', achse:'Maximum minus Minimum',
    abgrenzung:'Großer Sprung betrachtet den Netto-Tagesgewinn. Achterbahn fordert konkrete 10:0/0:10-Ergebnisse, nicht den Elo-Weg.',
    mind:'30 Laufbahnpartien und mindestens vier eigene Partien am betrachteten Berliner Kalendertag. Das ist eine Stichprobe, keine Elo-Leistungslatte.',
    rechnung:'Stand unmittelbar vor der ersten eigenen Tagespartie und kanonische Nachwerte der eigenen Partien betrachten. Höchster minus niedrigster Stand ergibt die Spanne; größte Tages-Spanne gewinnt. Prestige und fremde Tagesanfänge gehören nicht in diese Zahlen.',
    gegenbeispiel:'100→130→40→75→110 hat Spanne 90, aber Netto +10. 100→130→145→155→160 hat nur Spanne 60, obwohl der Tagesgewinn größer ist.',
    risiko:'Mehr Tagespartien bieten mehr Chancen auf größere Ausschläge. Deshalb eine neutrale Fügung, kein Beweis für Können. Tagesdatum, Start, Tief, Hoch, Ende und Spielzahl im Beleg zeigen.',
    story:'Ein bewegter Tag für Leo: Zwischen 40 und 130 Elo liegen 90 Punkte. Am Ende bleiben gegenüber dem Start trotzdem nur zehn mehr.',
    beleg:'Synthetischer Tagesverlauf mit vier Partien. Keine Fixture-Elo oder behauptete Live-Rekordhöhe.'
  },
  {
    id:'grenzverkehr', bereich:'rekorde', art:'fuegung', kategorie:'Fügungen', titel:'Der Grenzverkehr', status:'Direkt mit Partien ausbauen',
    frage:'Die längste Begegnungsfolge mit derselben Person, in der man jedes Mal zwischen gemeinsamem Team und Gegenseite wechselt.',
    wert:'6 Begegnungen', person:'Mit Leon · gegen Leon · im Wechsel', grafik:'erweiterung', bild:{typ:'bahn',felder:[['Zusammen'],['Gegen'],['Zusammen'],['Gegen'],['Zusammen'],['Gegen']],hinweis:'Sechs Begegnungen, fünf Seitenwechsel. Partien ohne Leon verändern diesen Personenfaden nicht.'},
    basis:'30 Laufbahnpartien', achse:'Teamseite bei jedem Wiedersehen',
    abgrenzung:'Wanderpass wechselt den Mitspielernamen, Pendler die Position. Doppelgesicht vergleicht Leistungen auf beiden Seiten. Hier zählt der fortgesetzte Seitenwechsel zu derselben Person.',
    mind:'30 Laufbahnpartien und bekannte Vierer-Aufstellungen. Jede erste bekannte Begegnung startet bei eins; keine Mindestfolge und keine Erfolgsquote. Ein Bestwert eins bleibt gültig.',
    rechnung:'Je Gegenüber einen chronologischen Begegnungsfaden führen: Partner oder Gegner. Die andere Seite verlängert, dieselbe Seite startet bei eins. Bekannte eigene Partien ohne dieses Gegenüber berühren seinen Faden nicht. Unvollständige eigene Aufstellungen unterbrechen alle laufenden Fäden, weil ein Wiedersehen darin verborgen sein könnte. Größte Folge zählt; eine neue Marke entsteht unmittelbar an der zugehörigen Partie.',
    gegenbeispiel:'Zusammen→gegen→zusammen ergibt drei Begegnungen, auch wenn andere Partien dazwischenliegen. Zehn Begegnungen hintereinander nur gegeneinander ergeben eins, nicht zehn.',
    risiko:'Keine Rang- oder Leistungsbehauptung. Mehr Begegnungen bieten mehr Suchgelegenheiten; alle Mithalter führen. Der Beleg zeigt die tatsächlichen Match-IDs und Teamseiten, nicht einen verschobenen Rivalitätszähler. Tage und Monate brechen einen bekannten Personenfaden nicht.',
    story:'Jane und Leon wechseln bei sechs Begegnungen jedes Mal die Seite. Mal gemeinsam, mal gegeneinander – die nächste Partie kann den Faden direkt verlängern.',
    beleg:'Synthetische Teamseitenfolge, keine behauptete Live-Marke. Kein Monatsabschluss erforderlich; der schließende beziehungsweise verlängernde Match-Timestamp ist der Zeitpunkt.'
  },
  {
    id:'spurwechsel', bereich:'rekorde', art:'fuegung', kategorie:'Fügungen', titel:'Der Spurwechsel', status:'Wechsel der Ausgangslage',
    frage:'Die längste durchgehende Folge, in der man vor jedem Spiel abwechselnd Favorit und Außenseiter ist. Ob man gewinnt, ist egal.',
    wert:'6 Partien', person:'Andere Erwartungen, nicht andere Ergebnisse', grafik:'erweiterung', bild:{typ:'bahn',felder:[['30 %'],['70 %'],['25 %'],['65 %'],['40 %'],['80 %'],['50 %','stop']]},
    basis:'30 Partien, bekannte Chancen', achse:'Favorit / Außenseiter im Wechsel',
    abgrenzung:'Wechselbad zählt Sieg und Niederlage, Pendler die Position. Hier wechselt nur die gespeicherte Anpfiff-Erwartung.',
    mind:'30 Laufbahnpartien. Chance unter 45 % ist Außenseiter, über 55 % Favorit. Die offene Zone einschließlich ihrer Grenzen und unbekannte Chancen unterbrechen. Keine zusätzliche Mindestfolge oder Siege erforderlich.',
    rechnung:'Eigene Partien chronologisch in diese festen Ausgangslagen einordnen. Jede bekannte Randlage startet bei eins; Wechsel zur anderen Randlage verlängert, gleiche Lage startet neu. Die offene Zone setzt auf null. Größter Lauf zählt, auch über Tage und Monate.',
    gegenbeispiel:'Sechs Niederlagen können trotzdem eine Spurwechsel-Folge von sechs Partien bilden. Sechs abwechselnde Siege/Pleiten mit stets 70 % Chance ergeben dagegen nur eins.',
    risiko:'Ein ausgeloster Verlauf, kein Leistungsbeleg. Chancenpendel der Monatsansicht betrachtet hingegen den ganzen kontinuierlichen Chanceverlauf gegenüber anderen Reihenfolgen. Die ähnliche Grafik macht die zwei Messfragen nicht identisch.',
    story:'Alex startet sechs Partien lang abwechselnd gegen und mit der Rechnung. Erst eine offene 50%-Partie beendet den Spurwechsel.',
    beleg:'Synthetische Anpfiffchancen zur Erklärung. Keine neue Elo- oder Siegchancenberechnung.'
  },
  {
    id:'doppelgesicht-allzeit', disziplinId:'doppelgesicht', bereich:'rekorde', art:'fuegung', kategorie:'Fügungen', titel:'Das Doppelgesicht', status:'Eine Disziplin, zwei Zeitachsen',
    frage:'Die größte Abweichung zwischen der eigenen Leistung neben einer Person und den Partien gegen genau diese Person – jeweils gegenüber der Anpfiff-Erwartung.',
    wert:'40 Punkte Abstand', person:'20 % neben / 15 % gegen · Beispiel', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Neben Leon','20 % Siege'],['Gegen Leon','15 % Siege'],['Soll daneben','25 %'],['Soll dagegen','60 %']],hinweis:'Soll-Abweichung −5 / −45 Punkte. Auch niedrige Quoten erzeugen einen echten Abstand.'},
    basis:'15 neben / 15 gegen', achse:'Dieselbe Beziehung, andere Seite',
    abgrenzung:'Katalysator vergleicht Partner mit/ohne den Spieler, Angstgegner eine Gegnerquote. Hier werden beide Teamseiten derselben Beziehung verglichen.',
    mind:'30 Laufbahnpartien und je fünfzehn bekannte gemeinsame beziehungsweise gegnerische Partien mit dem betreffenden Gegenüber. Keine Mindest-Siegquote oder geforderte Höhe des Abstands.',
    rechnung:'Je Gegenüber mittlere Soll-Abweichung R neben dieser Person und R gegen sie bilden. Wert = absoluter Abstand. Den größten gültigen Einzelwert halten, keine Personenwerte addieren. Ein Match zählt je Beziehungsgruppe genau einmal. Die gesamte Laufbahn ist die Zeitachse.',
    gegenbeispiel:'20 % bei Soll 25 % neben Leon und 15 % bei Soll 60 % gegen ihn ergeben |−5−(−45)|=40 Punkte. Zwei hohe Quoten exakt auf Soll ergeben dagegen null.',
    risiko:'Keine gemeinsame Duo-Auszeichnung: Der Wert beschreibt die Perspektive eines Spielers und ist nicht automatisch für beide gleich. Mehrere Gegenüber erzeugen Auswahlchancen; an mehr Daten prüfen. Selbst ein Bestwert null ist gültig und darf nicht als starker Kontrast ausgeschmückt werden.',
    story:'Gemeinsam und gegeneinander sind für Julian zwei verschiedene Bilder. Seine Soll-Abweichungen liegen bei Begegnungen mit Leon 40 Punkte auseinander.',
    beleg:'Synthetische Werte. Die Monatskarte verwendet dieselbe vorgeschlagene Disziplin doppelgesicht, nicht einen weiteren Namen für dieselbe Statistik.'
  },
  {
    id:'rivalitaetswende', bereich:'monate', art:'koennen', kategorie:'Können', titel:'Die Rivalitätswende', beiname:'Der Fadenwender', status:'Spezifischer Gegnerfaden',
    frage:'Gegen einen bestimmten Gegner geht es stärker aufwärts als im übrigen eigenen Monatsbild. Auch eine Wende von 10 auf 40 % zählt.',
    wert:'+40 Punkte spezifisch', person:'Neue Monatsquote nur 30 % · Beispiel', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Gegen Julian vorher','10 %'],['Gegen Julian jetzt','40 %'],['Rest vorher','30 %'],['Rest jetzt','20 %']],hinweis:'Anpfiff-Erwartung jeweils 40 %. Gegen Julian +30, im Rest −10 Punkte.'},
    basis:'8 je Gruppe und Monat', achse:'Gegneränderung minus Reständerung',
    abgrenzung:'Quantensprung misst die ganze Form, Ausbruch einen beendeten Bann. Hier verbessert sich ein bestimmter Faden über den allgemeinen Trend hinaus.',
    mind:'Vorgeschlagen acht Partien gegen J und acht ohne J in beiden vollständigen Monaten. J als Partner aus der Restgruppe ausschließen. Ausreichend Tage und bekannte Anpfiffchancen; keine Mindestquote.',
    rechnung:'V = (R_neu_gegenJ − R_alt_gegenJ) − (R_neu_ohneJ − R_alt_ohneJ). Sowohl die direkte Verbesserung gegen J als auch V müssen positiv sein. GegenJ und Rest sind disjunkte Matchgruppen, keine Liste aller anderen Gegnerbeobachtungen. Größten qualifizierten Faden belegen, nicht addieren.',
    gegenbeispiel:'Gegen Julian steigt die Quote von 10 auf 40 %, während sie im Rest von 30 auf 20 % fällt; bei gleichem Soll ergibt das +40 spezifische Punkte. Verbessert sich beides um 30, ist die spezifische Wende null.',
    risiko:'Zwei Gegner pro Match sind keine zwei unabhängigen Partien. Suche über mehrere Fäden und alte schlechte Gruppen kann Zufall oder Regression zur Mitte verstärken. Unterschiedliche Aufstellungen im Beleg zeigen, keine Rivalität als Ursache behaupten.',
    story:'Jannik verbessert seinen Faden gegen Julian deutlich, während das übrige Monatsbild nachlässt. Die Wende ist spezifisch – nicht einfach mehr Siege überall.',
    beleg:'Vier erfundene gleich große Zehnergruppen. Gesamtquote neu 30 %, dennoch ein positiver spezifischer Ausschlag.'
  },
  {
    id:'positionspakt', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Der Positionspakt', beiname:'Der Rollengekoppelte', status:'Umgedrehtes Rollenprofil',
    frage:'Die eigene bessere Position dreht sich bei einem bestimmten Mitspieler um. Nicht nur die Quote, sondern das Rollenprofil wechselt die Richtung.',
    wert:'20 / −10 Punkte', person:'Mit Leon vorne, sonst hinten · Beispiel', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Mit Leon · Sturm','+10'],['Mit Leon · Abwehr','−10'],['Ohne Leon · Sturm','−5'],['Ohne Leon · Abwehr','+5']],hinweis:'Soll-Abweichungen in Punkten. Rollenabstände +20 und −10: belegter Ausschlag 10.'},
    basis:'5 Partien in jeder der 4 Zellen', achse:'Rollenprofil mit / ohne Gegenüber',
    abgrenzung:'Spezialist misst den allgemeinen Rollenabstand, Kontrast Partnerquoten. Hier müssen zwei bedingte Rollenprofile wirklich gegensätzlich sein.',
    mind:'Vorgeschlagen fünf Partien in jeder der vier Gruppen, an mindestens drei eigenen Tagen. Bekannte Positionen und Chancen. Der ganze feste Monat zählt; keine ausgesuchten kurzen Phasen.',
    rechnung:'A = R_Sturm_mitJ − R_Abwehr_mitJ, B = R_Sturm_ohneJ − R_Abwehr_ohneJ. Nur bei A×B<0 liegt der Positionspakt vor. Wert = min(|A|,|B|), damit beide Richtungen belegt sind. Größten qualifizierten Wert nennen; beide Vorzeichenvarianten sind dieselbe Disziplin.',
    gegenbeispiel:'Mit Leon +20 Rollenabstand, ohne ihn −10 ergibt einen Richtungswechsel von mindestens zehn Punkten. +20 und +10 ist nur verschieden stark, aber kein umgedrehtes Profil.',
    risiko:'Partner-, Gegner- und Rollenverteilungen können gemeinsam wirken. Keine behauptete Chemie-Ursache. Mehrfachsuche über Partner prüfen. Positionsfehler nicht als zusätzliche Teilgruppe behandeln; unbekannte Positionen ausschließen und Anzahl nennen.',
    story:'Neben Leon zeigt Martin das günstigere Bild im Sturm. Ohne Leon liegt sein besseres Rollenbild in der Abwehr. Der Positionspakt dreht das Muster um.',
    beleg:'Erfundene Soll-Abweichungen, keine echten Positionsquoten oder persönliche Diagnose.'
  },
  {
    id:'startzeit', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Die Startzeit', beiname:'Der Zeitversetzte', status:'Gleiche Spielnummer, andere Uhrzeit',
    frage:'Die erste eigene Tagespartie fällt vor und ab 15 Uhr deutlich unterschiedlich gegenüber der Erwartung aus.',
    wert:'20 Punkte Abstand', person:'20 % früh / 40 % spät · Beispiel', grafik:'erweiterung', bild:{typ:'balken',zeilen:[['Auftakt vor 15','20 %',20,true],['Auftakt ab 15','40 %',40]],hinweis:'Soll jeweils 40 %. Verglichen werden Tagesauftakte, nicht spätere Spielnummern.'},
    basis:'5 eigene Tagesauftakte je Gruppe', achse:'Fester Uhrzeitschnitt',
    abgrenzung:'Kaltstart wertet alle Auftakte, zweite Luft frühe/spätere Spielnummern. Hier bleibt die Spielnummer auf beiden Seiten dieselbe.',
    mind:'Vorgeschlagen mindestens fünf Berliner Kalendertage je Uhrzeitgruppe, immer nur erste eigene Partie pro Tag. 15 Uhr ist ein vorab festes Konzept-Raster, keine nachträglich optimierte Grenze.',
    rechnung:'Absoluter Abstand zwischen mittlerer Soll-Abweichung der Auftakte vor 15 Uhr und jener ab 15 Uhr. Beide Richtungen gleich behandeln; keine absolute Siegquote als Voraussetzung. Die Zeitgrenze hat nichts mit dem Auslösen der Funfacts zu tun.',
    gegenbeispiel:'20 % bei 40 % Soll früh und 40 % bei 40 % Soll spät ergeben Abstand 20. Zehn zusätzliche Partien desselben späten Tages erhöhen die Stichprobe der Startzeit nicht.',
    risiko:'Kein biologischer Biorhythmus bewiesen. Andere Wochentage, Besetzung oder Zeitplanung können erklären, warum sich Gruppen unterscheiden. Je Gruppe Tage, Chancen und Zeitspanne sichtbar machen.',
    story:'Johannes startet vor und ab 15 Uhr mit unterschiedlichen Monatsbildern. Die Auftakte liegen 20 Punkte auseinander, ohne dass seine Gesamtquote hoch sein muss.',
    beleg:'Erfundene Beispielquoten. Der feste Uhrzeitschnitt muss vor einem Einbau auf ausreichend echte Tagesgruppen geprüft werden.'
  },
  {
    id:'bilanzparadox', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Das Bilanzparadox', beiname:'Der Gegenbucher', status:'Zwei Bilanzen widersprechen',
    frage:'Mehr Niederlagen als Siege, aber eine positive Torbilanz – oder mehr Siege bei negativer Torbilanz. Beide Richtungen zählen gemeinsam.',
    wert:'33 % Siege · 58 % Toranteil', person:'4 Siege / 8 Pleiten · 112:80 Tore', grafik:'erweiterung', bild:{typ:'balken',zeilen:[['Sieganteil','33 %',100/3,true],['Teamtoranteil','58 %',112/192*100]],hinweis:'Sieganteil unter 50 %, Teamtoranteil darüber. Beide stammen aus denselben zwölf Partien.'},
    basis:'12 vollständige Partien', achse:'Gemeinsames Monats-Gesamtbild',
    abgrenzung:'Deutlicher misst die Differenz, Punktlandung deren Ausgleich. Hier müssen zwei vollständige Bilanzen in entgegengesetzte Richtungen zeigen.',
    mind:'Vorgeschlagen zwölf gültige eigene Partien. Resultate und Teamtore aus exakt derselben Matchmenge. Keine hohe Quote und kein Mindesttorvorsprung.',
    rechnung:'q = Siege/Partien, t = Summe TeamtoreFür/(Summe TeamtoreFür + Summe TeamtoreGegen). Nur (q−0,5)×(t−0,5)<0 ist ein Paradox. Wert = min(|q−0,5|,|t−0,5|); beide Bilanzseiten müssen weg von ihrem Gleichstand. Ganze Summen, kein ungewichteter Mittelwert einzelner Torquoten.',
    gegenbeispiel:'Vier 10:0-Siege und acht 9:10-Pleiten ergeben 33,33 % Siege, aber 112:80 Tore und 58,33 % Teamtoranteil. Eine positive Tordifferenz allein oder exakt 50 % Siege reichen nicht für den Widerspruch.',
    risiko:'Verwandt mit knappen Pleiten und deutlichen Siegen, aber nur das gemeinsame Monatsaggregat ist der Anlass. Keine neue Clutch-Leistung behaupten. Teamtore sind keine persönlich geschossenen Tore. Vor Vergleich nicht runden.',
    story:'Maxi verliert mehr Partien, als er gewinnt, und steht trotzdem mit 32 Toren im Plus. Die beiden Bilanzen erzählen diesen Monat verschiedene Geschichten.',
    beleg:'Zwölf exakt konsistente synthetische Ergebnisse. Der Ausschlag beträgt 8,33 Prozentpunkte, keine erfundene Seltenheit.'
  },
  {
    id:'chancenpendel', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Das Chancenpendel', beiname:'Der Chancenpendler', status:'Reihenfolge der Erwartungen',
    frage:'Die Anpfiffchancen springen von Partie zu Partie ungewöhnlich stark – gegenüber anderen Reihenfolgen genau derselben Ausgangslagen.',
    wert:'+28,4 Punkte Wechsel', person:'Gleiche Chancen, zackigerer Spielplan', grafik:'erweiterung', bild:{typ:'weg',werte:[20,80,20,80,20,80,20,80],einheit:'% Chance',hinweis:'Illustration aus 20 Chancen: zehnmal 20 %, zehnmal 80 %, vollständig im Wechsel.'},
    basis:'20 Chancen, 3 eigene Tage', achse:'Übergangsgröße statt Lage',
    abgrenzung:'Schwerster Tag misst das Chancenmittel, Spurwechsel einen längsten binären Lauf. Hier zählt der kontinuierliche Übergang des ganzen Monats.',
    mind:'Vorgeschlagen zwanzig eigene Partien an drei Tagen mit bekannten Anpfiffchancen. Gleiche feste Monatsfolge, keine Suche nach einer günstigen kurzen Episode.',
    rechnung:'Beobachtet Mittel(|p_i−p_vorher|) über alle direkten eigenen Übergänge. Referenz = Summe aller geordneten |p_i−p_j| für i≠j geteilt durch N(N−1), also durchschnittlicher Übergang bei zufälliger Reihenfolge derselben Chancen. Größter positiver Überschuss gewinnt.',
    gegenbeispiel:'Zehn 20%- und zehn 80%-Chancen im Wechsel ergeben 60 Punkte je Übergang; Referenz 31,58, Überschuss 28,42. Dieselben Chancen in zwei Blöcken haben dieselbe Verteilung, aber nur 3,16 Punkte je Übergang.',
    risiko:'Keine neue Elo-Berechnung oder Aussage über Erfolge. Eine Reihenfolge-Referenz ist kein Elo-Wahrscheinlichkeitstest. Fehlende Chancen dürfen keine künstliche Verbindung über eine unbekannte Partie erzeugen; im Zweifel Monat nicht vollständig bewertbar.',
    story:'Leons Ausgangslagen pendeln stärker als gewöhnlich: Auf schwierige Partien folgen immer wieder günstige – die Siege spielen für diesen Anlass keine Rolle.',
    beleg:'Synthetisches Chancenmultiset mit exakt nachrechenbarer Reihenfolge-Referenz. Die Grafik zeigt einen verkürzten Ausschnitt.'
  },
  {
    id:'ergebnisdialekt', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Der Ergebnisdialekt', beiname:'Der Unverwechselbare', status:'Das ganze Ergebnisprofil',
    frage:'Die Mischung der Endstände in den eigenen Partien weicht am stärksten vom restlichen Ligamonat ab. Sieg und Niederlage sind dafür egal.',
    wert:'Ein anderes Monatsprofil', person:'Alle zehn Abstände gemeinsam vergleichen', grafik:'erweiterung', bild:{typ:'profil',eigen:[0,0,0,20,40,20,0,0,0,20],rest:[0,10,10,10,10,10,10,10,10,20],hinweis:'Endstände 10:0 bis 10:9, Richtung ignoriert. Eigene Partien / übrige Liga.'},
    basis:'20 eigene / 40 übrige Partien', achse:'Gesamtverteilung statt Lieblingszahl',
    abgrenzung:'Lieblingszahl betrachtet den häufigsten gerichteten Endstand, Torhagel einen Mittelwert. Hier zählt die ganze ungerichtete Verteilung.',
    mind:'Vorgeschlagen zwanzig eigene und vierzig übrige Ligapartien im festen Monat. Alle eigenen Matches aus der Ligareferenz entfernen; jede übrige Partie einmal zählen, nicht viermal als Spielerbeobachtung.',
    rechnung:'Verteilungen P und Q der niedrigeren Endstandseite 0 bis 9 bilden, wenn regulär auf zehn gespielt wird. Jensen-Shannon-Divergenz mit M=(P+Q)/2: ein halbes KL(P||M) plus ein halbes KL(Q||M), Logarithmus Basis 2. Nullterme tragen null bei. Größte Divergenz gewinnt, keine Siegquote nötig. Abweichende Endstandsregeln in beiden Gruppen ausschließen und ihre Anzahl nennen.',
    gegenbeispiel:'Gleicher Durchschnitt und gleicher häufigster Endstand garantieren nicht dieselbe Mischung der übrigen Resultate. Die Richtung 10:6 oder 6:10 wird hier absichtlich nicht als Spielererfolg verwendet.',
    risiko:'Kleine und dünn besetzte Profile können zufällig weit auseinanderliegen. Referenzgröße, Unsicherheit und normale Endstandsregeln vor Einbau prüfen. Bei zu wenig Restliga kein stiller Ersatz durch eigene Partien oder einen anderen Monat.',
    story:'Wenn Henry am Tisch steht, klingt der Monat anders: Seine Endstandmischung hebt sich vom übrigen Ligamonat ab, unabhängig davon, wer gewinnt.',
    beleg:'Erfundene Verteilungen mit je 100 % Gesamtanteil. Die Grafik ist eine beschreibende Verteilung, kein Vorhersage-Mosaik für das nächste Ergebnis.'
  },
  {
    id:'doppelgesicht-monat', disziplinId:'doppelgesicht', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Das Doppelgesicht', beiname:'Der Seitengetrennte', status:'Gleiche Disziplin wie im Rekord',
    frage:'Neben und gegen dieselbe Person entstehen diesen Monat die unterschiedlichsten eigenen Soll-Abweichungen. Beide Richtungen zählen.',
    wert:'40 Punkte Abstand', person:'Eine Messfrage auf Monatsachse', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Neben Leon · R','−5'],['Gegen Leon · R','−45']],hinweis:'Gleiche Formel wie im Allzeitrekord. Andere Zeitachse, keine zweite Disziplin.'},
    basis:'5 neben / 5 gegen, 3 Tage', achse:'Gemeinsam minus gegeneinander',
    abgrenzung:'Der gleichnamige Allzeitrekord verwendet dieselbe Formel über die Laufbahn. Keine neue Trennlinie-ID oder zweite Art von Kontrast.',
    mind:'Vorgeschlagen je fünf gemeinsame und gegnerische Partien mit demselben Gegenüber im festen Monat, an insgesamt drei eigenen Tagen. Bekannte historische Chancen; keine hohe Siegquote.',
    rechnung:'Genau wie Allzeit: je Gegenüber |R_neben − R_gegen|, größtes qualifiziertes Beziehungsbild. Beobachtungsgruppe und Datenquelle einmal berechnen; nur Zeitfenster und Stichprobe unterscheiden sich. Die größere Abweichung, nicht die höhere Gesamtquote, zählt.',
    gegenbeispiel:'Eine insgesamt schwache 20%-Quote neben Leon kann bei Soll 25 % weniger negativ auffallen als 15 % gegen ihn bei Soll 60 %. Die beobachtete Abweichung ist 40 Punkte, kein erfolgreicher Duo-Titel.',
    risiko:'Mehrfachsuche und kleine Teilgruppen bleiben prüfpflichtig. Jeder Match zählt in der eigenen Beziehungskategorie einmal; zwei Gegner sind nicht zwei unabhängige Fälle. Das Blatt darf die Gruppen nicht als Ursache der Leistung verkaufen.',
    story:'Julians Monat hat gegenüber Leon zwei Seiten: Zusammen und gegeneinander fällt seine Leistung gegenüber dem jeweiligen Soll deutlich unterschiedlich aus.',
    beleg:'Synthetisches identisches Grundbeispiel wie im Rekord. Vorgeschlagene gemeinsame Disziplin doppelgesicht mit monat/allzeit, nicht zwei App-Einträge.'
  },
  {
    id:'ruhiges-feld', bereich:'monate', art:'konstanz', kategorie:'Konstanz', titel:'Das ruhige Feld', beiname:'Der Gegnerfeste', status:'Gleichmäßiger gegenüber der Vorgeschichte',
    frage:'Die Unterschiede zwischen den eigenen Gegnerfäden werden gegenüber dem Vormonat kleiner – selbst wenn die gesamte Siegquote sinkt.',
    wert:'50 Punkte Glättung', person:'Gesamtquote 40 → 25 % · Beispiel', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Vorher · Spanne','0 bis 80 %'],['Jetzt · Spanne','10 bis 40 %']],hinweis:'Gleiche vier Gegner, gleiche Anpfiff-Erwartung. Abstände schrumpfen, Niveau steigt nicht.'},
    basis:'4 feste Gegner, je 5 pro Monat', achse:'Gegnerstreuung vorher / jetzt',
    abgrenzung:'Angstfrei verlangt gute Leistung gegen alle. Quantensprung misst die Formhöhe. Hier wird nur das persönliche Gegnerfeld gleichmäßiger.',
    mind:'Alle Gegner mit mindestens fünf Begegnungen im Vormonat bilden die Kohorte; mindestens vier müssen es sein. Diese komplette vorher festgelegte Kohorte muss im neuen Monat wieder jeweils fünf Begegnungen haben. Fehlende Fäden nicht durch null ersetzen oder nachträglich aussortieren.',
    rechnung:'Je Monat für genau diese Gegner die mittleren Soll-Abweichungen bilden. S = höchster minus niedrigster Gegner-R-Wert. Ausschlag = S_alt − S_neu, nur bei echter Verkleinerung. Alle vorher qualifizierten Gegner einbeziehen; nicht die vier schönsten jetzigen Gruppen suchen.',
    gegenbeispiel:'Bei gleicher Erwartung schrumpfen Gegnerquoten 0/20/60/80 % zu 10/20/30/40 %. Die Spanne sinkt von 80 auf 30 Punkte, obwohl die mittlere Quote von 40 auf 25 % fällt.',
    risiko:'In 2v2 überlappen Gegnerfäden: Ein Match gegen A und B ist keine doppelte unabhängige Beobachtung. Alte Extremgruppen und Stichprobenrauschen können von selbst glatter werden; Unsicherheit mitprüfen und keine allgemeine Formverbesserung behaupten.',
    story:'Janes Gegnerfeld wird ruhiger. Die Unterschiede zwischen denselben vier Fäden schrumpfen um 50 Punkte, obwohl der Monat insgesamt weniger Siege bringt.',
    beleg:'Erfundene, gleich groß belegte Gegnergruppen mit identischem Soll. Diese vier Gegner decken im Beispiel alle eigenen Partien ab; deshalb entspricht ihr Gruppenmittel der Monatsquote. Keine Behauptung einer statistisch kalibrierten Chronik.'
  }
];
