'use strict';
// Eigenständige Monatsvorschläge. Nur synthetische Erklärungen, keine Live-Auswertung.
// Gemeinsame kanonische Eingaben später einmal auswerten, niemals Elo im Mockup nachrechnen.
window.BESONDERHEITEN_MONATSMUSTER = [
  {
    id:'seitenbuendnis', bereich:'monate', art:'koennen', kategorie:'Können', titel:'Das Seitenbündnis', beiname:'Der Seitenverbinder', status:'Gegner werden Mitspieler',
    frage:'Nach einem Partnerwechsel fällt die eigene Leistung günstiger gegenüber der Erwartung aus, wenn der neue Mitspieler eben noch auf der Gegenseite stand.',
    wert:'+30 Punkte', person:'Auch mit niedrigen Quoten · Beispiel', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Bisheriger Gegner','40 % Siege'],['Andere Wechsel','10 % Siege'],['Soll beider Gruppen','40 %'],['Soll-Abweichungen','0 / −30 Punkte']],hinweis:'Beide Gruppen sind echte Partnerwechsel. Die erste eigene Tagespartie gehört zu keiner Gruppe.'},
    basis:'5 je Wechselart · 3 Tage', achse:'Herkunft des neuen Partners',
    abgrenzung:'Staffellauf vergleicht Wechsel gegen Nichtwechsel. Hier wechseln beide Gruppen ihren Partner; neu ist dessen vorherige Gegenseite. Wanderpass zählt eine Folge, keine Leistung in solchen Situationen.',
    mind:'Vorgeschlagen mindestens fünf Partien je Wechselart an insgesamt drei eigenen Berliner Spieltagen. Unmittelbar vorherige eigene Partie desselben Tages mit bekannten vier Spielern und Partnerzuordnung. Keine hohe Siegquote als Voraussetzung.',
    rechnung:'Erste eigene Tagespartien ausschließen. Nur tatsächliche Wechsel des eigenen Partners aufnehmen. Gehört der neue Partner zu den beiden Gegnern der unmittelbar vorherigen eigenen Partie, ist es ein Seitenbündnis; sonst ein anderer Partnerwechsel. In beiden disjunkten Gruppen R = Mittelwert(Siegindikator minus gespeicherte Anpfiffchance) bilden. Wert = R_Seitenbündnis minus R_andere_Wechsel, nur wenn positiv. Fehlende Aufstellungen nicht überspringen.',
    gegenbeispiel:'Je zehn gewertete Wechselpartien: 40 % bei Soll 40 % nach dem Seitenbündnis, 10 % bei Soll 40 % nach anderen Wechseln ergeben +30 Punkte. Die zwanzig Wechselpartien haben zusammen nur 25 % Siege; die ausgenommenen Auftakte gehören nicht in diese Beispielquote. Ein bloß guter Partnerwechsel ohne vorherige Gegenseite beweist dieses Muster nicht.',
    risiko:'Alte Gegner und völlig neue Mitspieler treten häufig in unterschiedlichen Aufstellungen auf. Rollen, Gegner, Tage und Stichproben sichtbar machen; keine kausale Wirkung des Bündnisses behaupten. Jeder aktuelle Match zählt einmal. Die frühere eigene Partie liefert nur den Kontext, keinen zweiten Erfolgsbeitrag.',
    story:'Nach einem Seitenbündnis zeigt Jane ein günstigeres Bild als nach anderen Partnerwechseln. Der Unterschied beträgt 30 Punkte gegenüber der Rechnung – nicht einfach eine hohe Monatsquote.',
    beleg:'Synthetische, gleich große Wechselgruppen. Keine echten Ergebnisse von Jane und keine gemessene Seltenheit. Historische Chancen später aus derselben kanonischen Quelle wie bei Staffellauf.'
  },
  {
    id:'gegnergeflecht', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Das Gegnergeflecht', beiname:'Der Verflechtete', status:'Zusammen anders als einzeln',
    frage:'Zwei Gegner zusammen erzeugen ein anderes persönliches Monatsbild, als aus den getrennten Begegnungen mit ihnen und dem übrigen Feld hervorgeht.',
    wert:'30 Punkte Verflechtung', person:'Auch bei 32,5 % Siegen · Beispiel', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Gegen J und K','−40'],['Nur gegen J','−10'],['Nur gegen K','−10'],['Ohne beide','−10']],hinweis:'Vier disjunkte Matchgruppen. Werte sind Soll-Abweichungen in Prozentpunkten; der Interaktionswert beträgt −30.'},
    basis:'5 Partien je Gruppe · 3 Tage', achse:'Vier Gruppen, eine Interaktion',
    abgrenzung:'Angstgegner und Rivalitätswende betrachten einen Gegnerfaden. Doppelgesicht vergleicht beide Teamseiten derselben Person. Hier wird die gemeinsame gegnerische Besetzung über ihre getrennten Bilder hinaus betrachtet.',
    mind:'Vorgeschlagen fünf gültige Partien in jeder der vier Gruppen an mindestens drei eigenen Tagen des festen Monats. J und K müssen verschieden sein. Jede Partie mit J oder K als eigenem Partner ist aus allen vier Gruppen ausgeschlossen. Bekannte Gegner und historische Anpfiffchancen.',
    rechnung:'R_11 gegen J und K, R_10 gegen J ohne K, R_01 gegen K ohne J, R_00 ohne J und K bilden. Ohne bedeutet wirklich abwesend, nicht bloß auf der Partnerseite. Die Gruppen sind disjunkt. Wert je Gegenüberpaar = abs(R_11 minus R_10 minus R_01 plus R_00). Größten qualifizierten Einzelwert belegen, keine Paare addieren. Beide Interaktionsrichtungen gehören zur selben Disziplin.',
    gegenbeispiel:'Vier Zehnergruppen bei jeweils 50 % Soll: 10/40/40/40 % Siege ergeben R = −40/−10/−10/−10 und Interaktion −30, Betrag 30. Gesamtquote nur 32,5 %. Wird ein gemeinsamer Nachteil exakt durch die beiden getrennten Effekte erklärt, ist der zusätzliche Interaktionswert null.',
    risiko:'Viele mögliche Gegnerpaare schaffen Suchgelegenheiten; Unsicherheit und Auswahlbreite prüfen. Aufstellungen, Rollen und Chancen können gemeinsam wirken. Kein Beweis gegnerischer Chemie, kein gemeinsamer Duo-Titel für J und K. Ein Match ist auch gegen zwei Gegner nur eine eigene Beobachtung.',
    story:'Für Jannik ist das gemeinsame Gegnerbild von Julian und Leon auffällig: Es weicht zusätzlich von den getrennten Begegnungen ab. Das Geflecht beschreibt Janniks Perspektive, nicht einen neuen Titel für das Duo.',
    beleg:'Synthetische vier Zehnergruppen mit identischer Erwartung. Die Namen illustrieren den Anlass, keine ausgelesenen Gegnerstatistiken.'
  },
  {
    id:'gegnerbalance', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Die Gegnerbalance', beiname:'Der Gefälleleser', status:'Unterschiede innerhalb des Gegenteams',
    frage:'Die eigene Soll-Abweichung unterscheidet sich bei Gegnerteams mit größerem und kleinerem internem Elo-Gefälle gegenüber einer vorher festgelegten Grenze.',
    wert:'20 Punkte Abstand', person:'10 / 30 % Siege · Beispiel', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Festes altes Raster','80 Elo Abstand'],['Gefälle bis 80','10 % Siege'],['Gefälle über 80','30 % Siege'],['Soll jeweils','40 %']],hinweis:'Die Grenze stammt aus Gegner-Abständen des vollständigen Vormonats, nicht aus der Suche nach dem größten Erfolgskontrast.'},
    basis:'12 alte Werte · 5 je neuer Gruppe', achse:'Fester Ursprung, anderer Gegnerbau',
    abgrenzung:'Gegnergeflecht untersucht bestimmte Personenpaare. Schwerster Tag mittelt Siegchancen. Hier zählt die Verteilung der Stärke innerhalb des Gegenteams, nicht dessen Identität, Gesamtstärke oder die eigene Monatsquote.',
    mind:'Vorgeschlagen zwölf bekannte Gegner-Elo-Abstände im vollständigen Vormonat. Im aktuellen ganzen Monat mindestens fünf Partien je Gruppe an insgesamt drei eigenen Tagen; je Gruppe mindestens zwei unterschiedliche Gegnerpaare. Kanonische ungerundete Vor-Match-Elo beider Gegner und Anpfiffchancen erforderlich.',
    rechnung:'Je Match g = abs(Elo_vor_Gegner1 minus Elo_vor_Gegner2). Median aller gültigen eigenen g des Vormonats als festen Schnitt b bilden, bei gerader Zahl das Mittel der beiden mittleren Werte. Aktuelle Partien einmal in g<=b oder g>b einteilen. Wert = abs(R_obere_Gruppe minus R_untere_Gruppe). Den Schnitt vor Betrachtung des aktuellen Effekts festlegen und niemals auf den größten Abstand optimieren. Ohne Vormonatsbasis keine Ersatzgrenze null.',
    gegenbeispiel:'Alte Gegner-Abstände 20/40/60/70/70/80/80/90/100/100/120/150 haben Median 80 Elo. Aktuelle Zehnergruppen mit 10 beziehungsweise 30 % Siegen stehen beide bei 40 % Soll. Residualwerte −30/−10 ergeben 20 Punkte Abstand trotz nur 20 % aktueller Siege. Derselbe Erwartungswert garantiert nicht dieselbe interne Besetzung des Gegenteams.',
    risiko:'Ein höheres Gefälle bedeutet nur höher als das eigene feste Raster, nicht automatisch ein besonders starkes Gegnerteam. Rollenbesetzung, eigener Partner und Gegneridentitäten können den Effekt erklären. Kein neues Elo-Modell und keine Aussage, dass ungleiche Gegner leichter seien. Fehlende Elo nicht durch null ergänzen.',
    story:'Martins Monat zeigt zwei Gegnerbilder: Bei größerem internem Gefälle fällt seine Leistung anders gegenüber der Rechnung aus als bei ausgeglicheneren Gegnerteams. Die Vergleichsgrenze stand schon vor dem Effekt fest.',
    beleg:'Synthetischer Median und zwei aktuelle Zehnergruppen. Später vorhandene kanonische eloBefore-Daten verwenden; keine Rückrechnung aus heutigen Elo und kein Live-Rekord behaupten.'
  },
  {
    id:'rueckspielwelle', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Die Rückspielwelle', beiname:'Der Rückspielpendler', status:'Unveränderte Aufstellung, anderes Resultat',
    frage:'Direkte Rückspielpaare mit identischen Teams und Positionen wechseln den Sieger häufiger als andere Reihenfolgen derselben Ergebnisse in diesen Aufstellungen.',
    wert:'+10,5 Punkte Wechsel', person:'Nur 25 % Siege · Beispiel', grafik:'erweiterung', bild:{typ:'bahn',felder:[['S→N'],['S→N'],['S→N'],['S→N'],['S→N'],['N→N'],['N→N'],['N→N'],['N→N'],['N→N']],hinweis:'Zehn disjunkte Paare, fünf Siege und fünfzehn Niederlagen. Die Paarbildung steht unabhängig von den Ergebnissen fest.'},
    basis:'5 Rückspielpaare · 3 Tage', achse:'Beide Richtungen, gleicher Spielrahmen',
    abgrenzung:'Retourkutsche zählt Siege beim nächsten Wiedersehen nach einer Pleite gegen ein Gegnerduo. Hier zählen beide Resultatwechsel in unveränderten Teams und Positionen. Wechselbad ist ein längster Lauf; Spiegelmonat und Tagesumkehr haben andere feste Vergleichsrahmen.',
    mind:'Vorgeschlagen fünf disjunkte direkte Rückspielpaare an mindestens drei eigenen Berliner Tagen. In jedem Paar müssen Partner, beide Gegner und die Positionen aller vier Spieler bekannt und identisch sein. Fester ganzer Monat, kein Paar über seine Grenze.',
    rechnung:'Eigene chronologische Partien nach Timestamp und stabiler Match-ID lesen. Frühestes noch ungenutztes direkt benachbartes Paar gleicher Aufstellung am selben Tag aufnehmen, danach beide Partien verbrauchen; sonst um eine Partie weitergehen. Ergebnis nie zur Paarwahl verwenden. A = Resultatwechsel/Paarzahl. Je identischer Aufstellung c die gesamten gültigen Monatsresultate W_c,L_c,N_c als Referenz nehmen: b_c = 2*W_c*L_c/[N_c*(N_c−1)]. B ist das nach Paarzahl M_c gewichtete Mittel dieser b_c. Wert A−B, nur wenn positiv.',
    gegenbeispiel:'Eine identische Aufstellung mit zwanzig Monatsresultaten, fünf Siegen und fünfzehn Pleiten: zehn feste Paare zeigen fünfmal S→N, fünfmal N→N. A=50 %, B=39,4737 %, Überschuss 10,5263 Punkte. Die Paare können über drei Tage verteilt sein. Ein Siegüberschuss ist nicht erforderlich; die ungepaarten und übrigen Resultate einer Aufstellung bleiben in deren Referenz.',
    risiko:'Die Referenz permutiert Ergebnislabels innerhalb derselben Monatsaufstellung; sie hält die Paarstellen fest, nicht die Tages-Siegzahlen. Kein Elo-Wahrscheinlichkeitstest und keine unabhängigen Paarversuche behaupten. Gesamte Folgen gemeinsam prüfen. Unbekannte Rollen oder wechselnde Aufstellung nicht als Rückspiel behandeln. Team-A/B-Labelwechsel allein verändert die personengebundene Aufstellung nicht.',
    story:'Bei Leos direkten Rückspielen bleibt die Besetzung stehen, das Resultat aber oft nicht. Fünf von zehn festen Paaren wechseln den Sieger – häufiger als im Reihenfolge-Vergleich derselben Aufstellung.',
    beleg:'Synthetische zwanzig Resultate und zehn ergebnisunabhängig gebildete Paare. Exakte Reihenfolge-Referenz, keine gemessene Sigma-Zahl und kein Beweis einer Revanche-Fähigkeit.'
  },
  {
    id:'doppelzone', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Die Doppelzone', beiname:'Der Doppelrandige', status:'Enge und klare Partien, wenig dazwischen',
    frage:'Sowohl enge als auch klare Endstände treten im eigenen Monat häufiger auf als in der übrigen Liga. Erst beide Überschüsse zusammen ergeben die gerichtete U-Form.',
    wert:'Beide Ränder +20 Punkte', person:'Sieger ist für das Profil egal', grafik:'erweiterung', bild:{typ:'profil',eigen:[10,10,10,10,5,5,5,5,20,20],rest:[5,5,5,5,15,15,15,15,10,10],hinweis:'Niedrigere Endstandseite 0–9: klare Abstände mindestens 7 links, enge höchstens 2 rechts. Beide Ränder größer, die Mitte kleiner als in der Restliga.'},
    basis:'20 eigene · 40 Restliga-Partien', achse:'Zwei gerichtete Profilüberschüsse',
    abgrenzung:'Ergebnisdialekt misst jede Art von Verteilungsabweichung. Doppelzone verlangt ausdrücklich beide Ränder gegen dieselbe Referenz. Nervenkitzel betrachtet nur enge Partien, Torhagel nur den Mittelwert. Kein weiterer allgemeiner JS-Abstand.',
    mind:'Vorgeschlagen zwanzig eigene und vierzig übrige gültige Ligapartien im selben ganzen Monat. Reguläre Endstände auf zehn, Abstände 1 bis 10. Jede eigene Partie aus der Restliga entfernen; dort jeden Match einmal zählen. Kein Mindest-Sieganteil.',
    rechnung:'Ungerichteten Abstand d=abs(Teamtore_für minus Teamtore_gegen) bilden. Feste Zonen: eng d<=2, mittel 3<=d<=6, klar d>=7. A = Anteil_eng_eigen minus Anteil_eng_Rest, B = Anteil_klar_eigen minus Anteil_klar_Rest. Nur A>0 und B>0 belegen die U-Form. Wert = min(A,B), damit nicht ein großer einzelner Rand den fehlenden zweiten ersetzt. Beide Verteilungen und ihre gemeinsame vollständige Basis zeigen.',
    gegenbeispiel:'Zwanzig eigene Partien haben 8 enge, 4 mittlere und 8 klare Endstände: 40/20/40 %. Vierzig Restligapartien haben 8/24/8: 20/60/20 %. Beide Ränder +20 Punkte, Ausschlag 20. Eigene 80 % enge und 0 % klare Partien können stark abweichen, erfüllen die Doppelzone aber nicht.',
    risiko:'Kuriose Endstandmischung, keine Clutch-Fähigkeit oder Anzahl Kantersiege. Die Ergebnisrichtung ist egal, eine schwache Quote kann dasselbe Profil besitzen. Kleine Restliga und besetzungsbedingte Endstände prüfen; bei fehlender Referenz keine eigene Datenbasis zurückmischen. Unbekannte oder abweichende Endstandsregeln in beiden Gruppen ausschließen und Anzahl nennen.',
    story:'Henrys Partien liegen diesen Monat häufiger an beiden Rändern: besonders eng oder besonders klar. Die Mitte wird seltener – ein Doppelprofil statt nur mehr knapper Spiele.',
    beleg:'Synthetische ganzzahlige Verteilungen aus 20 eigenen und 40 übrigen Matches. Beide Profilreihen summieren sich auf 100 %. Keine Siegprognose und keine gemessene Seltenheit.'
  },
  {
    id:'torwende', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Die Torwende', beiname:'Der Gegenstrebige', status:'Häufigkeit und Höhe laufen auseinander',
    frage:'Die Siegquote und die Höhe der Niederlagen verändern sich in widersprüchliche Qualitätsrichtungen: weniger Siege, aber näher dran – oder mehr Siege, aber höhere Pleiten.',
    wert:'20 Punkte Gegenbewegung', person:'40 → 20 % Siege · 6 → 2 Tore', grafik:'erweiterung', bild:{typ:'matrix',zellen:[['Siegquote vorher','40 %'],['Siegquote jetzt','20 %'],['Pleitenabstand vorher','6 Tore'],['Pleitenabstand jetzt','2 Tore']],hinweis:'Weniger Siege, kleinere Niederlagen. In beiden Monaten ist die Torbilanz weiterhin negativ; kein Bilanzparadox.'},
    basis:'12 je Monat · 5 Pleiten je Monat', achse:'Feste Monate, zwei Qualitätsrichtungen',
    abgrenzung:'Widerstand misst den niedrigen absoluten Niederlagenabstand. Bilanzparadox gegensätzliche Gesamtbilanzen in einem Monat. Hier zählt ein Widerspruch zwischen deren Veränderungen und der bedingten Höhe eigener Niederlagen.',
    mind:'Vorgeschlagen jeweils zwölf gültige eigene Partien und mindestens fünf Niederlagen an ausreichend Tagen in beiden vollständigen Monaten. Der Vormonat ist fest; keine Suche nach einem besonders schlechten Abschnitt. Keine Mindestquote und kein geforderter Torvorsprung.',
    rechnung:'Je Monat q=Siege/alle gültigen Partien und m=Mittelwert(Teamtore_gegen minus Teamtore_für) ausschließlich über die eigenen Niederlagen. Delta_q=q_neu−q_alt, Delta_m=m_neu−m_alt. Nur Delta_q*Delta_m>0 ist die gegenläufige Qualität: steigende Quote und höherer Pleitenabstand oder fallende Quote und kleinerer Abstand. Wert=min(abs(Delta_q),abs(Delta_m)/10), bei regulären Spielen auf zehn. Beide Vorzeichenvarianten sind eine Disziplin.',
    gegenbeispiel:'Vorher acht 10:9-Siege und zwölf 4:10-Pleiten, jetzt vier 10:9-Siege und sechzehn 8:10-Pleiten. Quote 40→20 %, mittlerer Pleitenabstand 6→2. Delta_q=−0,20, Delta_m/10=−0,40, Ausschlag 0,20. Torbilanzen −64 und −28 bleiben beide negativ; das Bilanzparadox ist nicht erfüllt. Weniger Pleiten und zugleich kleinere Pleiten wären kein Gegenlauf.',
    risiko:'Keine allgemeine Verbesserung und kein Comeback innerhalb einer Partie behaupten. Der Nenner der Torhöhe sind Niederlagen, der der Quote alle Matches; beide Basen nennen. Andere Gegner und geänderte Erwartungen können das Bild erklären. Die Normalisierung durch zehn ist eine erklärte Konzeptskala, kein statistisches Gütesiegel.',
    story:'Maxi gewinnt seltener, verliert aber deutlich knapper. Die Monatsquote sinkt, der mittlere Abstand seiner Pleiten zugleich von sechs auf zwei Tore – zwei gegenläufige Seiten desselben Monatsvergleichs.',
    beleg:'Zwei vollständig konsistente synthetische Zwanziger-Monate. Teamtore, nicht persönlich geschossene Tore. Kein Zwischenstand und keine Live-Leistungsdiagnose.'
  },
  {
    id:'verdichtung', bereich:'monate', art:'fuegung', kategorie:'Fügung', titel:'Die Verdichtung', beiname:'Der Näherkommende', status:'Der ganze Monat wird enger',
    frage:'Die Endstände werden im Verlauf des gesamten Monats systematisch enger – unabhängig davon, ob die eigenen Siege häufiger werden.',
    wert:'τ = 0,973 · Beispiel', person:'Auch mit 6 Siegen aus 20 möglich', grafik:'erweiterung', bild:{typ:'weg',werte:[10,9,8,7,6,5,4,3,2,1],einheit:'Tore Abstand',hinweis:'Verkürzte Bahn: In den zwanzig Beispielpartien tritt jeder Abstand zweimal unmittelbar hintereinander auf. Die Ergebnisrichtungen sind frei.'},
    basis:'20 Partien · 3 eigene Tage', achse:'Zeitliche Ordnung statt Profilhöhe',
    abgrenzung:'Nervenkitzel zählt enge Partien, Ergebnisdialekt deren Verteilung, Gleichmut eine Streuung. Hier zählt ihre gerichtete Reihenfolge über den ganzen Monat. Kein neuer Monatsleiter-Rekord und keine Suche nach einer engen Teilfolge.',
    mind:'Vorgeschlagen zwanzig gültige eigene Monats-Partien an mindestens drei Tagen. Ganze feste Monatsfolge nach Timestamp und stabiler Match-ID; reguläre Endstände und bekannte Teamtore. Keine hohe Siegquote und keine Mindesthöhe des Trends.',
    rechnung:'Für i<j Abstand d_i=abs(Teamtore_für minus Teamtore_gegen) vergleichen. C zählt Paare mit d_j<d_i, D solche mit d_j>d_i; T zählt gleiche Abstände. P=N*(N−1)/2. Wert ist Kendall-tau-b für Zeitindex gegen negativen Abstand: (C−D)/sqrt(P*(P−T)). Nur positive Werte belegen die Verdichtung. Falls P−T=0, gibt es keinen bestimmbaren Trend; weder null als Ersatzvergleich noch eine erfundene perfekte Verdichtung einsetzen.',
    gegenbeispiel:'Abstände 10,10,9,9,...,1,1 haben N=20, P=190, T=10, C=180 und D=0: tau=180/sqrt(190*180)=0,97333. Sechs beliebig verteilte Siege und vierzehn Pleiten ändern diesen ungerichteten Trend nicht. Dieselben Abstände rückwärts haben dieselbe Verteilung und denselben Anteil enger Partien, aber einen negativen Trend.',
    risiko:'Der Koeffizient ist ein beschreibender Rangtrend, keine Siegchance, keine Prozentpunkte und kein Sigma-Test. Ganze Folgen und Spieltage gemeinsam prüfen, Paarvergleiche nicht als unabhängige Versuche behandeln. Wechselnde Besetzung kann die Verdichtung erklären; keine persönliche Fähigkeit oder Entwicklung der geschossenen Einzelspielertore behaupten.',
    story:'Julians Partien rücken im Monatsverlauf näher zusammen. Nicht mehr Siege, sondern immer kleinere Endstandsabstände prägen den Weg – der ganze Monat zählt, nicht nur eine gute Schlussphase.',
    beleg:'Synthetische zwanzig Abstände mit exakt nachrechenbarem Kendall-tau-b. Die verkürzte Grafik zeigt das Muster, keine ausgelesenen Matches und keinen kalibrierten Seltenheitswert.'
  }
];
