// Eingaben bleiben synchron; teure Vorschau-/Sucharbeit wird je Bild gebündelt.
// Verhaltens- und Arbeitszusicherungen statt geräteabhängiger Zeitgrenzen.
if(!require('./browser.js').ladeChromium()){
  console.log('ÜBERSPRUNGEN — kein Chromium verfügbar.');
  console.log('  Fokus, Tastatur und Eingabe-Bündelung brauchen einen Browser.');
  process.exit(2);
}
const {createHarness}=require('../tools/performance.cjs');
let checks=0,fails=0;
const ok=(c,msg)=>{checks++;if(!c)fails++;console.log((c?'  ok  ':'  ✗   ')+msg);};
(async()=>{
  const {browser,page,K,errors}=await createHarness();
  try{
    await K(`window.__computeMatch=computeMatch;window.__inputCalls=0;
      computeMatch=(...a)=>{window.__inputCalls++;return window.__computeMatch(...a)};
      window.__draft=()=>{M={A1:players[0].id,A2:players[1].id,B1:players[2].id,B2:players[3].id,pA1:'atk',pA2:'def',pB1:'atk',pB2:'def',sa:10,sb:4};tab='match';render()};
      window.__draft();window.__inputCalls=0;invalidateCache();updatePreview();0;`);
    ok(await K('__inputCalls===1'),'Gültige Vorschau nutzt eine kanonische Match-Rechnung für Chance und Deltas');
    await K('window.__inputCalls=0;window.__chance=document.querySelector(".m-chance");updatePreview();0;');
    ok(await K('__inputCalls===0'),'Unveränderte Vorschau rechnet nicht erneut');
    await K('M.sb=5;updatePreview();0;');
    ok(await K('__inputCalls===1 && document.querySelector(".m-chance")===window.__chance'),'Scorewechsel rechnet nur den Stand und behält das unveränderte Chancen-DOM');
    ok(await K(`typeof _matchInputResult==='function' && JSON.stringify(_matchInputResult())===JSON.stringify(window.__computeMatch(...Object.values(teamsFromM()),'A',10,5))`),'Memo-Ergebnis entspricht exakt der kanonischen Engine');
    await K('window.__inputCalls=0;invalidateCache();updatePreview();0;');
    ok(await K('__inputCalls===1'),'Datenversion invalidiert die letzte Eingabe-Rechnung');
    await K('window.__inputCalls=0;cfg={...cfg,k_factor:cfg.k_factor+1};updatePreview();0;');
    ok(await K('__inputCalls===1'),'Konfigurationsreferenz invalidiert die letzte Eingabe-Rechnung');
    await K('window.__inputCalls=0;players=[...players];updatePreview();0;');
    ok(await K('__inputCalls===1'),'Spielerreferenz invalidiert die letzte Eingabe-Rechnung');
    await K('window.__inputCalls=0;matches=[...matches];updatePreview();0;');
    ok(await K('__inputCalls===1'),'Matchreferenz invalidiert die letzte Eingabe-Rechnung');
    await K('window.__inputCalls=0;window.__perfJetzt=new Date(2026,8,1,12).getTime();updatePreview();0;');
    ok(await K('__inputCalls===1'),'Monatswechsel invalidiert die letzte Eingabe-Rechnung');

    await K(`window.__raf=requestAnimationFrame;window.__frames=[];
      window.requestAnimationFrame=fn=>{window.__frames.push(fn);return window.__frames.length};
      window.cancelAnimationFrame=()=>{};window.__draft();window.__inputCalls=0;
      document.querySelector('[data-step="sb,1"]').click();
      document.querySelector('[data-step="sb,1"]').click();
      document.querySelector('[data-step="sb,1"]').click();0;`);
    ok(await K('M.sb===7 && document.getElementById("svB").textContent==="7"'),'Drei schnelle Score-Tipps sind sofort im Zustand und im sichtbaren Stand');
    ok(await K('__inputCalls===0 && window.__frames.length===1'),'Schnelle Score-Tipps planen genau eine Vorschau statt drei Rechnungen');
    await K('window.__frames.shift()?.();0;');
    ok(await K('__inputCalls===1 && document.getElementById("previewSlot").textContent.includes("10:7")'),'Das nächste Bild zeigt den letzten Stand mit einer Rechnung');
    await K(`document.querySelector('[data-step="sb,1"]').click();window.__alt=window.__frames.shift();
      document.getElementById('clearM').click();window.__inputCalls=0;window.__alt?.();0;`);
    ok(await K('__inputCalls===0 && document.getElementById("previewSlot").textContent===""'),'Alte Vorschau verändert kein nach Leeren neu gebautes Formular');

    await K(`window.__draft();document.getElementById('svB').click();
      window.__score=document.querySelector('.sval-input');window.__score.value='8';
      window.__score.dispatchEvent(new Event('input',{bubbles:true}));0;`);
    ok(await K('M.sb===8 && !document.getElementById("saveM").disabled'),'Direkte Toreingabe aktualisiert Zustand und Speichern ohne Blur');
    await K(`window.__score.value='10';window.__score.dispatchEvent(new Event('input',{bubbles:true}));0;`);
    ok(await K('M.sb===10 && document.getElementById("saveM").disabled'),'Unentschieden sperrt Speichern bereits während der Eingabe');
    await K(`window.__score.value='99';window.__score.dispatchEvent(new Event('input',{bubbles:true}));0;`);
    ok(await K('M.sb===10 && window.__score.value==="10"'),'Direkte Toreingabe bleibt innerhalb derselben 0-bis-10-Grenze');
    await K(`window.__score.value='';window.__score.dispatchEvent(new Event('input',{bubbles:true}));0;`);
    ok(await K('M.sb===0 && window.__score.value===""'),'Leere Zahl ist im Zustand null ohne den laufenden Tipp zu überschreiben');
    await K('window.__score.blur();window.__frames=[];0;');

    await K(`M.A1='';render();window.__combo=document.querySelector('[data-combo="A1"]');
      window.__combo.focus();window.__combo.dispatchEvent(new CompositionEvent('compositionstart'));
      window.__combo.value='Al';window.__combo.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));
      window.__combo.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true,isComposing:true}));0;`);
    ok(await K('M.A1==="" && document.activeElement===window.__combo'),'IME-Enter wählt keinen Spieler und verliert keinen Fokus');
    await K(`window.__combo.dispatchEvent(new CompositionEvent('compositionend'));
      window.__down=new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true});
      window.__combo.dispatchEvent(window.__down);0;`);
    ok(await K(`window.__down.defaultPrevented && !!window.__combo.getAttribute('aria-activedescendant')`),'Pfeiltaste wählt eine erreichbare Option ohne den Cursor zu verschieben');
    await K(`window.__enter=new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true});window.__combo.dispatchEvent(window.__enter);0;`);
    ok(await K('M.A1===players[0].id && window.__enter.defaultPrevented'),'Enter übernimmt den fokussierten Spieler genau einmal');
    await K(`window.__combo.onfocus();window.__combo.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));0;`);
    ok(await K(`window.__combo.getAttribute('aria-expanded')==='false' && !document.querySelector('[data-combolist="A1"]').classList.contains('show')`),'Escape schließt die Vorschläge mit korrektem ARIA-Zustand');
    await K(`window.__combo.blur();window.__combo.focus();0;`);
    await page.waitForTimeout(210);
    ok(await K(`document.querySelector('[data-combolist="A1"]').classList.contains('show')`),'Alter Blur-Timer schließt keine sofort wieder fokussierte Vorschlagsliste');
    await K(`window.__combo.onfocus();window.__pick=document.querySelector('[data-combolist="A1"] [data-pick]').dataset.pick;0;`);
    await page.locator('[data-combolist="A1"] [data-pick]').first().click();
    ok(await K('M.A1===window.__pick && document.activeElement===window.__combo'),'Pointer-Auswahl übernimmt den Spieler ohne die Eingabetastatur durch Fokusverlust zu schließen');

    await K(`window.requestAnimationFrame=window.__raf;tab='teams';teamSearch='';render();
      window.__search=document.getElementById('teamSearch');window.__search.focus();
      window.__search.value='Leon';window.__search.setSelectionRange(2,2);
      window.__search.dispatchEvent(new Event('input',{bubbles:true}));0;`);
    await page.waitForTimeout(360);
    ok(await K('document.getElementById("teamSearch")===window.__search && document.activeElement===window.__search && window.__search.selectionStart===2'),'Teamsuche behält Eingabeknoten, Fokus und Cursor beim Aktualisieren');
    ok(await K(`[...document.querySelectorAll('.tm-name')].every(x=>x.textContent.includes('Leon')) && document.querySelectorAll('.tm-name').length>0`),'Teamsuche aktualisiert passende Duos aus der gemeinsamen Vorlage');
    await K(`window.requestAnimationFrame=fn=>{window.__frames.push(fn);return window.__frames.length};window.__frames=[];
      window.__search.dispatchEvent(new CompositionEvent('compositionstart'));window.__search.value='Martin';
      window.__search.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));0;`);
    ok(await K('window.__frames.length===0'),'Laufende IME-Komposition wird nicht durch Ergebnisarbeit unterbrochen');
    await K(`window.__search.dispatchEvent(new CompositionEvent('compositionend'));0;`);
    ok(await K('window.__frames.length===1'),'Kompositionsende plant die letzte Suche einmal');
    await K(`tab='match';render();window.__frames.shift()?.();0;`);
    ok(await K('document.getElementById("saveM") && !document.getElementById("teamSearch")'),'Veraltete Suche überschreibt nach Tabwechsel keine andere Ansicht');

    await K(`window.requestAnimationFrame=window.__raf;window.__draft();window.__insertions=0;
      window.__from=sb.from;sb.from=table=>table==='matches'?{insert(row){window.__insertions++;window.__row=row;
        return {select(){return {single(){return new Promise(resolve=>window.__saveResolve=resolve)}}}}}}:window.__from(table);
      window.__saveFirst=doSaveMatch();window.__saveSecond=doSaveMatch();0;`);
    ok(await K('window.__insertions===1 && document.getElementById("saveM").disabled'),'Doppeltes Speichern schreibt nur eine Partie und sperrt den Knopf sofort');
    ok(await K('document.getElementById("saveM").getAttribute("aria-busy")==="true"'),'Speichern zeigt den laufenden Vorgang unmittelbar an');
    await K(`window.__saveResolve({error:{message:'Testfehler'}});0;`);
    await page.waitForTimeout(10);
    ok(await K('!document.getElementById("saveM").disabled && M.sa===10 && M.sb===4 && !doSaveMatch._busy'),'Fehlgeschlagenes Speichern erhält die Eingabe und gibt einen neuen Versuch frei');
    await K(`window.__persist=persistNewMatch;window.__earned=badgesEarnedInMatch;window.__load=loadAll;
      persistNewMatch=async()=>{};badgesEarnedInMatch=()=>[];loadAll=async()=>{};
      window.__saveFirst=doSaveMatch();M.sb=6;tab='teams';render();
      window.__saveResolve({data:{...window.__row,id:'gespeicherter-test',created_at:new Date().toISOString()}});0;`);
    await K('window.__saveFirst.catch(()=>null)');
    ok(await K(`matches.find(m=>m.id==='gespeicherter-test').score_b===4 && M.sb===6`),'Späte Speicherantwort behält den neuen Entwurf und speichert den ursprünglichen Stand');
    ok(await K('tab==="teams" && !!document.getElementById("teamSearch")'),'Späte Speicherantwort holt den Nutzer nicht in einen verlassenen Reiter zurück');
    await K(`window.__draft();persistNewMatch=async()=>{throw new Error('erwarteter Folgefehler')};
      window.__saveFirst=doSaveMatch();window.__saveResolve({data:{...window.__row,id:'folgefehler-test',created_at:new Date().toISOString()}});0;`);
    await K('window.__saveFirst.catch(()=>null)');
    ok(await K(`matches.some(m=>m.id==='folgefehler-test') && M.A1==='' && document.getElementById('saveM').disabled && !doSaveMatch._busy`),'Fehler nach erfolgreichem Insert hinterlässt keine erneut speicherbare Kopie');
    await K(`persistNewMatch=window.__persist;badgesEarnedInMatch=window.__earned;loadAll=window.__load;0;`);
    await K(`window.__recalc=persistRecalc;persistRecalc=async()=>{};loadAll=async()=>{};
      sb.from=window.__from;showEditMatch(matches[matches.length-1].id);
      E.sa=10;document.getElementById('esvA').textContent='10';document.querySelector('[data-estep="sa,1"]').click();0;`);
    ok(await K('E.sa===10 && document.getElementById("esvA").textContent==="10"'),'Bearbeitungs-Score nutzt dieselbe obere Grenze wie die neue Eingabe');
    await K(`window.__editWrites=0;window.__editResolves=[];sb.from=table=>table==='matches'?{update(row){window.__editWrites++;window.__editRow=row;
      return {eq(){return new Promise(resolve=>{window.__editResolve=resolve;window.__editResolves.push(resolve)})}}}}:window.__from(table);
      window.__editClick=document.getElementById('saveEdit').onclick;window.__editFirst=window.__editClick();window.__editClick();0;`);
    ok(await K('window.__editWrites===1 && document.getElementById("saveEdit").disabled'),'Doppeltipp auf Bearbeitung schreibt nur einmal und sperrt sofort');
    await K(`while(window.__editResolves.length) window.__editResolves.shift()({error:{message:'erwarteter Editfehler'}});0;`);
    await K('window.__editFirst');
    ok(await K('!document.getElementById("saveEdit").disabled && document.getElementById("sheet").classList.contains("show")'),'Fehlgeschlagene Bearbeitung bleibt offen und kann erneut gespeichert werden');
    await K(`persistRecalc=async list=>{window.__editUpdated=list.find(m=>m.id===E.id)};
      window.__editFirst=window.__editClick();document.querySelector('[data-estep="sb,1"]').click();0;`);
    ok(await K('document.getElementById("saveEdit").disabled'),'Bearbeitung bleibt auch bei weiteren Eingaben während des Speicherns gesperrt');
    await K('window.__editResolve({});0;');
    await K('window.__editFirst');
    ok(await K('window.__editUpdated.score_b===4 && E.sb===5 && document.getElementById("sheet").classList.contains("show")'),'Späte Editantwort berechnet den ursprünglichen Stand und erhält einen inzwischen geänderten Entwurf');
    await K('persistRecalc=window.__recalc;loadAll=window.__load;0;');
    await K('sb.from=window.__from;0;');
    await K(`window.__draft();openSheet('<select data-pos="A1"><option value="def" selected>Andere Rolle im Blatt</option></select>');readM();0;`);
    ok(await K('M.pA1==="atk"'),'Match-Eingabe liest nur ihr eigenes Formular und keine gleich benannten Blattfelder');
    await K(`openSheet('<button data-detail="'+players[0].id+'" id="sheetOwnClick">Eigener Blatt-Link</button>');
      window.__sheetHandler=()=>{};document.getElementById('sheetOwnClick').onclick=window.__sheetHandler;
      tab='ranking';render();0;`);
    ok(await K('document.getElementById("sheetOwnClick").onclick===window.__sheetHandler'),'Neuzeichnen der Hauptansicht bindet keine Links eines offenen Blatts um');
    ok(errors.length===0,'Keine Browserfehler während der Eingabefolge');
  }finally{await browser.close()}
  console.log(fails?`${fails} von ${checks} CHECKS FEHLGESCHLAGEN`:`ALLE ${checks} CHECKS BESTANDEN`);
  process.exit(fails?1:0);
})().catch(e=>{console.error(e);process.exit(1)});
